# Generated by Django 4.2.1 on 2023-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecomparison',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
