# Generated by Django 4.2.1 on 2023-05-27 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0002_alter_pricecomparison_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecomparison',
            name='cs',
        ),
        migrations.DeleteModel(
            name='ComaparetiveStatement',
        ),
        migrations.DeleteModel(
            name='PriceComparison',
        ),
    ]
