# Generated by Django 4.2.1 on 2023-05-31 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tendering', '0003_remove_pricecomparison_cs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparetiveStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('apprx_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendering.comparetivestatement')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendering.comparetivestatement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendering.item')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tendering.vendor')),
            ],
        ),
    ]
